/*
-- LAB: BigQuery - NYC Yellow Taxi Exercises
-- Student: Guillermo Fiallo-Montero
-- Table: bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
-- Note: Using 2022 data as 2023 table not available
*/

-- Using the NYC Taxi public dataset (Yellow Trips) from Google BigQuery, complete the following exercises:

-- Exercise 1: Count the number of trips in January 2023 (January 2022 used instead)

SELECT COUNT(*) 
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
WHERE EXTRACT(MONTH FROM pickup_datetime) = 1;
-- Result: 2,463,954

-- Exercise 2: Calculate the total revenue generated by taxi trips in 2023
SELECT 
  SUM(total_amount) AS total_revenue,
  SUM(fare_amount + extra + mta_tax + tip_amount + tolls_amount + imp_surcharge) AS sum_of_components
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`;
-- Result: 2,463,954


-- Exercise 3: Find the most popular pickup location

Select pickup_location_id as most_popular_pu, COUNT(pickup_location_id) as nr_of_pu
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
GROUP BY pickup_location_id
ORDER BY nr_of_pu DESC
LIMIT 1;

-- Exercise 4: Analyze the number of trips per hour of the day
SELECT EXTRACT(HOUR FROM pickup_datetime) AS hour, COUNT(pickup_datetime) AS nr_trips
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
GROUP BY hour
ORDER BY hour;

-- Exercise 5: Calculate the average trip distance
SELECT ROUND(avg(trip_distance),2) AS avg_trip_distance
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022;

-- Exercise 6: Find the longest trip by distance
SELECT trip_distance
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
ORDER BY trip_distance DESC
LIMIT 1;

-- Exercise 7: Calculate the total number of passengers by payment type
SELECT 
  payment_type,
  SUM(passenger_count) AS total_passangers
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
GROUP BY payment_type;

/* Result:
[{
  "payment_type": "1",
  "total_passangers": "38232144"
}, {
  "payment_type": "4",
  "total_passangers": "265749"
}, {
  "payment_type": "3",
  "total_passangers": "210382"
}, {
  "payment_type": "2",
  "total_passangers": "10292210"
}, {
  "payment_type": "0",
  "total_passangers": null
}, {
  "payment_type": "5",
  "total_passangers": "6"
}]
*/


-- Exercise 8: Find the most common drop-off location for trips paid by credit card
SELECT
  dropoff_location_id,
  COUNT(*) AS drop_off_count,
  payment_type
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
WHERE payment_type = "1"
GROUP BY dropoff_location_id, payment_type
ORDER BY drop_off_count DESC
LIMIT 1;

/* Result:
[{
  "dropoff_location_id": "236",
  "drop_off_count": "1236603",
  "payment_type": "1"
}]
*/

-- Exercise 9: Calculate the total number of trips that had more than 4 passengers

SELECT
  passenger_count,
  count(*) AS total_trips
FROM bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022
WHERE passenger_count > 4
GROUP BY passenger_count
ORDER BY total_trips;

-- Result: [{
  "passenger_count": "9",
  "total_trips": "39"
}, {
  "passenger_count": "8",
  "total_trips": "133"
}, {
  "passenger_count": "7",
  "total_trips": "208"
}, {
  "passenger_count": "6",
  "total_trips": "426667"
}, {
  "passenger_count": "5",
  "total_trips": "635766"
}]

-- Exercise 10: Subquery - Find the average fare for trips longer than the average trip distance

SELECT 
  Round(avg(fare_amount),2) AS avg_fare
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
WHERE  trip_distance > 
  (SELECT avg(trip_distance) FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`);

-- Result: 39.07 $

-- V2: CTE
WITH overall_avg AS(
  SELECT avg(trip_distance) as avg_distance
  FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
)

SELECT 
  ROUND(avg(fare_amount),2) AS avg_fare
FROM `bigquery-public-data.new_york_taxi_trips.tlc_yellow_trips_2022`
WHERE  trip_distance > 
  (SELECT avg_distance FROM overall_avg);
